### ISSUE TITLE
[suggestion] Expand value lists automatically into a list of jobs

### ISSUE THREAD

**Issue by jotaf98** [ExpectationMax/simple_gpu_scheduler#1]
First of all, thanks, this is really nice!

I was wondering if, adhering to the "KISS" principle even more, you could optionally skip stdin and instead give a single command with values to expand, e.g.:

`echo "echo job_id={1,2,3} device=\$CUDA_VISIBLE_DEVICES && sleep 3" | simple_gpu_scheduler --gpus 0,1,2`

would be expanded to 3 jobs taking those values.

Having more values to expand could get the product of those (like a grid search over all combinations of some parameters).

Although you could always do it using shell for loops as you showed, I think that this could be even more user-friendly, especially for large grid searches.

**Comment by ExpectationMax** [comment]
I'm glad you like the tool :)
Your suggestion sounds like a great addition!
I would solely prefer having the functionality disentangled in a different script. This way the `{}` characters would not have a special meaning for the scheduler script, avoiding the requirement to escape these characters if they are ever used in a command.

I gave it a shot and implemented something similar to what you suggested in a dedicated `simple_hypersearch` script. I'm not entirely happy with the calling syntax though and think it might have been better to stick closer to what you suggested. That would have required some sort of "tiny templating engine" though.
Nevertheless, in the current implementation the users can at least use the full power of python format strings and reuse values at different positions in the same command.
I'd be happy to hear what you think of it :)

**Comment by jotaf98** [comment]
This is great! I was gonna suggest random search but thought it might be too much to ask at once.

I think that the syntax and composability are spot-on. I would only suggest a documentation change to keep the simple use-case at the front -- maybe put the full description of command-line arguments in a separate markdown file, and keep only a few simple examples in the readme? Anyway just a suggestion.

**Comment by ExpectationMax** [comment]
I tried to tidy up the Readme a bit and make it more compact. 
I'll close the issue for now, feel free to reopen in case there are any further questions/suggestions.

**Comment by jotaf98** [comment]
Yep that's much less daunting, it's a nice intro!
