### ISSUE TITLE
GPLv3 -> MIT License

### ISSUE THREAD

**Issue by PiotrCzapla** [ExpectationMax/simple_gpu_scheduler#4]
Hi Max,
I've found your repo after searching for simple gpu aware batch job queues, that could fit the workflow of a DL Scientist and would work on any cloud or on a workstation. 
I'd rather build based on something already there, but the license is too restrictive for most  applications I have in mind. Would you consider changing the license to MIT or Apache? 

Cheers,
Piotr

**Comment by ExpectationMax** [comment]
Dear Piotr,

I am considering switching to the BSD 3 clause license.
Would that also fit for you?

Cheers,
Max

**Comment by PiotrCzapla** [comment]
Sure that is much better than GPLv3
